/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GateadoRouteRouteImport } from './routes/_gateado/route'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as GateadoIndexRouteImport } from './routes/_gateado/index'
import { Route as GateadoAuditoriaRouteImport } from './routes/_gateado/auditoria'
import { Route as GateadoBackupRouteImport } from './routes/_gateado/backup'
import { Route as GateadoCategoriasRouteImport } from './routes/_gateado/categorias'
import { Route as GateadoComparativaRouteImport } from './routes/_gateado/comparativa'
import { Route as GateadoCompromisosRouteImport } from './routes/_gateado/compromisos'
import { Route as GateadoConciliacionesRouteImport } from './routes/_gateado/conciliaciones'
import { Route as GateadoCuentasRouteImport } from './routes/_gateado/cuentas'
import { Route as GateadoDashboardRouteImport } from './routes/_gateado/dashboard'
import { Route as GateadoDiagnosticoRouteImport } from './routes/_gateado/diagnostico'
import { Route as GateadoFacturasRouteImport } from './routes/_gateado/facturas'
import { Route as GateadoFichaRouteImport } from './routes/_gateado/ficha'
import { Route as GateadoInformesRouteImport } from './routes/_gateado/informes'
import { Route as GateadoMovimientosRouteImport } from './routes/_gateado/movimientos'
import { Route as GateadoProveedoresRouteImport } from './routes/_gateado/proveedores'
import { Route as GateadoSnapshotsRouteImport } from './routes/_gateado/snapshots'
import { Route as GateadoTransferenciasRouteImport } from './routes/_gateado/transferencias'
import { Route as GateadoValidacionRouteImport } from './routes/_gateado/validacion'
import { Route as GateadoVencimientosRouteImport } from './routes/_gateado/vencimientos'
import { Route as GateadoFacturasNuevaRouteImport } from './routes/_gateado/facturas.nueva'

const GateadoRouteRoute = GateadoRouteRouteImport.update({
  id: '/_gateado',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const GateadoIndexRoute = GateadoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GateadoRouteRoute,
} as any)
const GateadoAuditoriaRoute = GateadoAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => GateadoRouteRoute,
} as any)
const GateadoBackupRoute = GateadoBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => GateadoRouteRoute,
} as any)
const GateadoCategoriasRoute = GateadoCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => GateadoRouteRoute,
} as any)
const GateadoComparativaRoute = GateadoComparativaRouteImport.update({
  id: '/comparativa',
  path: '/comparativa',
  getParentRoute: () => GateadoRouteRoute,
} as any)
const GateadoCompromisosRoute = GateadoCompromisosRouteImport.update({
  id: '/compromisos',
  path: '/compromisos',
  getParentRoute: () => GateadoRouteRoute,
} as any)
const GateadoConciliacionesRoute = GateadoConciliacionesRouteImport.update({
  id: '/conciliaciones',
  path: '/conciliaciones',
  getParentRoute: () => GateadoRouteRoute,
} as any)
const GateadoCuentasRoute = GateadoCuentasRouteImport.update({
  id: '/cuentas',
  path: '/cuentas',
  getParentRoute: () => GateadoRouteRoute,
} as any)
const GateadoDashboardRoute = GateadoDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => GateadoRouteRoute,
} as any)
const GateadoDiagnosticoRoute = GateadoDiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => GateadoRouteRoute,
} as any)
const GateadoFacturasRoute = GateadoFacturasRouteImport.update({
  id: '/facturas',
  path: '/facturas',
  getParentRoute: () => GateadoRouteRoute,
} as any)
const GateadoFichaRoute = GateadoFichaRouteImport.update({
  id: '/ficha',
  path: '/ficha',
  getParentRoute: () => GateadoRouteRoute,
} as any)
const GateadoInformesRoute = GateadoInformesRouteImport.update({
  id: '/informes',
  path: '/informes',
  getParentRoute: () => GateadoRouteRoute,
} as any)
const GateadoMovimientosRoute = GateadoMovimientosRouteImport.update({
  id: '/movimientos',
  path: '/movimientos',
  getParentRoute: () => GateadoRouteRoute,
} as any)
const GateadoProveedoresRoute = GateadoProveedoresRouteImport.update({
  id: '/proveedores',
  path: '/proveedores',
  getParentRoute: () => GateadoRouteRoute,
} as any)
const GateadoSnapshotsRoute = GateadoSnapshotsRouteImport.update({
  id: '/snapshots',
  path: '/snapshots',
  getParentRoute: () => GateadoRouteRoute,
} as any)
const GateadoTransferenciasRoute = GateadoTransferenciasRouteImport.update({
  id: '/transferencias',
  path: '/transferencias',
  getParentRoute: () => GateadoRouteRoute,
} as any)
const GateadoValidacionRoute = GateadoValidacionRouteImport.update({
  id: '/validacion',
  path: '/validacion',
  getParentRoute: () => GateadoRouteRoute,
} as any)
const GateadoVencimientosRoute = GateadoVencimientosRouteImport.update({
  id: '/vencimientos',
  path: '/vencimientos',
  getParentRoute: () => GateadoRouteRoute,
} as any)
const GateadoFacturasNuevaRoute = GateadoFacturasNuevaRouteImport.update({
  id: '/nueva',
  path: '/nueva',
  getParentRoute: () => GateadoFacturasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof GateadoIndexRoute
  '/unlock': typeof UnlockRoute
  '/auditoria': typeof GateadoAuditoriaRoute
  '/backup': typeof GateadoBackupRoute
  '/categorias': typeof GateadoCategoriasRoute
  '/comparativa': typeof GateadoComparativaRoute
  '/compromisos': typeof GateadoCompromisosRoute
  '/conciliaciones': typeof GateadoConciliacionesRoute
  '/cuentas': typeof GateadoCuentasRoute
  '/dashboard': typeof GateadoDashboardRoute
  '/diagnostico': typeof GateadoDiagnosticoRoute
  '/facturas': typeof GateadoFacturasRouteWithChildren
  '/ficha': typeof GateadoFichaRoute
  '/informes': typeof GateadoInformesRoute
  '/movimientos': typeof GateadoMovimientosRoute
  '/proveedores': typeof GateadoProveedoresRoute
  '/snapshots': typeof GateadoSnapshotsRoute
  '/transferencias': typeof GateadoTransferenciasRoute
  '/validacion': typeof GateadoValidacionRoute
  '/vencimientos': typeof GateadoVencimientosRoute
  '/facturas/nueva': typeof GateadoFacturasNuevaRoute
}
export interface FileRoutesByTo {
  '/unlock': typeof UnlockRoute
  '/auditoria': typeof GateadoAuditoriaRoute
  '/backup': typeof GateadoBackupRoute
  '/categorias': typeof GateadoCategoriasRoute
  '/comparativa': typeof GateadoComparativaRoute
  '/compromisos': typeof GateadoCompromisosRoute
  '/conciliaciones': typeof GateadoConciliacionesRoute
  '/cuentas': typeof GateadoCuentasRoute
  '/dashboard': typeof GateadoDashboardRoute
  '/diagnostico': typeof GateadoDiagnosticoRoute
  '/facturas': typeof GateadoFacturasRouteWithChildren
  '/ficha': typeof GateadoFichaRoute
  '/informes': typeof GateadoInformesRoute
  '/movimientos': typeof GateadoMovimientosRoute
  '/proveedores': typeof GateadoProveedoresRoute
  '/snapshots': typeof GateadoSnapshotsRoute
  '/transferencias': typeof GateadoTransferenciasRoute
  '/validacion': typeof GateadoValidacionRoute
  '/vencimientos': typeof GateadoVencimientosRoute
  '/': typeof GateadoIndexRoute
  '/facturas/nueva': typeof GateadoFacturasNuevaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_gateado': typeof GateadoRouteRouteWithChildren
  '/unlock': typeof UnlockRoute
  '/_gateado/auditoria': typeof GateadoAuditoriaRoute
  '/_gateado/backup': typeof GateadoBackupRoute
  '/_gateado/categorias': typeof GateadoCategoriasRoute
  '/_gateado/comparativa': typeof GateadoComparativaRoute
  '/_gateado/compromisos': typeof GateadoCompromisosRoute
  '/_gateado/conciliaciones': typeof GateadoConciliacionesRoute
  '/_gateado/cuentas': typeof GateadoCuentasRoute
  '/_gateado/dashboard': typeof GateadoDashboardRoute
  '/_gateado/diagnostico': typeof GateadoDiagnosticoRoute
  '/_gateado/facturas': typeof GateadoFacturasRouteWithChildren
  '/_gateado/ficha': typeof GateadoFichaRoute
  '/_gateado/informes': typeof GateadoInformesRoute
  '/_gateado/movimientos': typeof GateadoMovimientosRoute
  '/_gateado/proveedores': typeof GateadoProveedoresRoute
  '/_gateado/snapshots': typeof GateadoSnapshotsRoute
  '/_gateado/transferencias': typeof GateadoTransferenciasRoute
  '/_gateado/validacion': typeof GateadoValidacionRoute
  '/_gateado/vencimientos': typeof GateadoVencimientosRoute
  '/_gateado/': typeof GateadoIndexRoute
  '/_gateado/facturas/nueva': typeof GateadoFacturasNuevaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/unlock'
    | '/auditoria'
    | '/backup'
    | '/categorias'
    | '/comparativa'
    | '/compromisos'
    | '/conciliaciones'
    | '/cuentas'
    | '/dashboard'
    | '/diagnostico'
    | '/facturas'
    | '/ficha'
    | '/informes'
    | '/movimientos'
    | '/proveedores'
    | '/snapshots'
    | '/transferencias'
    | '/validacion'
    | '/vencimientos'
    | '/facturas/nueva'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/unlock'
    | '/auditoria'
    | '/backup'
    | '/categorias'
    | '/comparativa'
    | '/compromisos'
    | '/conciliaciones'
    | '/cuentas'
    | '/dashboard'
    | '/diagnostico'
    | '/facturas'
    | '/ficha'
    | '/informes'
    | '/movimientos'
    | '/proveedores'
    | '/snapshots'
    | '/transferencias'
    | '/validacion'
    | '/vencimientos'
    | '/'
    | '/facturas/nueva'
  id:
    | '__root__'
    | '/_gateado'
    | '/unlock'
    | '/_gateado/auditoria'
    | '/_gateado/backup'
    | '/_gateado/categorias'
    | '/_gateado/comparativa'
    | '/_gateado/compromisos'
    | '/_gateado/conciliaciones'
    | '/_gateado/cuentas'
    | '/_gateado/dashboard'
    | '/_gateado/diagnostico'
    | '/_gateado/facturas'
    | '/_gateado/ficha'
    | '/_gateado/informes'
    | '/_gateado/movimientos'
    | '/_gateado/proveedores'
    | '/_gateado/snapshots'
    | '/_gateado/transferencias'
    | '/_gateado/validacion'
    | '/_gateado/vencimientos'
    | '/_gateado/'
    | '/_gateado/facturas/nueva'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  GateadoRouteRoute: typeof GateadoRouteRouteWithChildren
  UnlockRoute: typeof UnlockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_gateado': {
      id: '/_gateado'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GateadoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_gateado/': {
      id: '/_gateado/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof GateadoIndexRouteImport
      parentRoute: typeof GateadoRouteRoute
    }
    '/_gateado/auditoria': {
      id: '/_gateado/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof GateadoAuditoriaRouteImport
      parentRoute: typeof GateadoRouteRoute
    }
    '/_gateado/backup': {
      id: '/_gateado/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof GateadoBackupRouteImport
      parentRoute: typeof GateadoRouteRoute
    }
    '/_gateado/categorias': {
      id: '/_gateado/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof GateadoCategoriasRouteImport
      parentRoute: typeof GateadoRouteRoute
    }
    '/_gateado/comparativa': {
      id: '/_gateado/comparativa'
      path: '/comparativa'
      fullPath: '/comparativa'
      preLoaderRoute: typeof GateadoComparativaRouteImport
      parentRoute: typeof GateadoRouteRoute
    }
    '/_gateado/compromisos': {
      id: '/_gateado/compromisos'
      path: '/compromisos'
      fullPath: '/compromisos'
      preLoaderRoute: typeof GateadoCompromisosRouteImport
      parentRoute: typeof GateadoRouteRoute
    }
    '/_gateado/conciliaciones': {
      id: '/_gateado/conciliaciones'
      path: '/conciliaciones'
      fullPath: '/conciliaciones'
      preLoaderRoute: typeof GateadoConciliacionesRouteImport
      parentRoute: typeof GateadoRouteRoute
    }
    '/_gateado/cuentas': {
      id: '/_gateado/cuentas'
      path: '/cuentas'
      fullPath: '/cuentas'
      preLoaderRoute: typeof GateadoCuentasRouteImport
      parentRoute: typeof GateadoRouteRoute
    }
    '/_gateado/dashboard': {
      id: '/_gateado/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof GateadoDashboardRouteImport
      parentRoute: typeof GateadoRouteRoute
    }
    '/_gateado/diagnostico': {
      id: '/_gateado/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof GateadoDiagnosticoRouteImport
      parentRoute: typeof GateadoRouteRoute
    }
    '/_gateado/facturas': {
      id: '/_gateado/facturas'
      path: '/facturas'
      fullPath: '/facturas'
      preLoaderRoute: typeof GateadoFacturasRouteImport
      parentRoute: typeof GateadoRouteRoute
    }
    '/_gateado/ficha': {
      id: '/_gateado/ficha'
      path: '/ficha'
      fullPath: '/ficha'
      preLoaderRoute: typeof GateadoFichaRouteImport
      parentRoute: typeof GateadoRouteRoute
    }
    '/_gateado/informes': {
      id: '/_gateado/informes'
      path: '/informes'
      fullPath: '/informes'
      preLoaderRoute: typeof GateadoInformesRouteImport
      parentRoute: typeof GateadoRouteRoute
    }
    '/_gateado/movimientos': {
      id: '/_gateado/movimientos'
      path: '/movimientos'
      fullPath: '/movimientos'
      preLoaderRoute: typeof GateadoMovimientosRouteImport
      parentRoute: typeof GateadoRouteRoute
    }
    '/_gateado/proveedores': {
      id: '/_gateado/proveedores'
      path: '/proveedores'
      fullPath: '/proveedores'
      preLoaderRoute: typeof GateadoProveedoresRouteImport
      parentRoute: typeof GateadoRouteRoute
    }
    '/_gateado/snapshots': {
      id: '/_gateado/snapshots'
      path: '/snapshots'
      fullPath: '/snapshots'
      preLoaderRoute: typeof GateadoSnapshotsRouteImport
      parentRoute: typeof GateadoRouteRoute
    }
    '/_gateado/transferencias': {
      id: '/_gateado/transferencias'
      path: '/transferencias'
      fullPath: '/transferencias'
      preLoaderRoute: typeof GateadoTransferenciasRouteImport
      parentRoute: typeof GateadoRouteRoute
    }
    '/_gateado/validacion': {
      id: '/_gateado/validacion'
      path: '/validacion'
      fullPath: '/validacion'
      preLoaderRoute: typeof GateadoValidacionRouteImport
      parentRoute: typeof GateadoRouteRoute
    }
    '/_gateado/vencimientos': {
      id: '/_gateado/vencimientos'
      path: '/vencimientos'
      fullPath: '/vencimientos'
      preLoaderRoute: typeof GateadoVencimientosRouteImport
      parentRoute: typeof GateadoRouteRoute
    }
    '/_gateado/facturas/nueva': {
      id: '/_gateado/facturas/nueva'
      path: '/nueva'
      fullPath: '/facturas/nueva'
      preLoaderRoute: typeof GateadoFacturasNuevaRouteImport
      parentRoute: typeof GateadoFacturasRoute
    }
  }
}

interface GateadoFacturasRouteChildren {
  GateadoFacturasNuevaRoute: typeof GateadoFacturasNuevaRoute
}

const GateadoFacturasRouteChildren: GateadoFacturasRouteChildren = {
  GateadoFacturasNuevaRoute: GateadoFacturasNuevaRoute,
}

const GateadoFacturasRouteWithChildren = GateadoFacturasRoute._addFileChildren(
  GateadoFacturasRouteChildren,
)

interface GateadoRouteRouteChildren {
  GateadoAuditoriaRoute: typeof GateadoAuditoriaRoute
  GateadoBackupRoute: typeof GateadoBackupRoute
  GateadoCategoriasRoute: typeof GateadoCategoriasRoute
  GateadoComparativaRoute: typeof GateadoComparativaRoute
  GateadoCompromisosRoute: typeof GateadoCompromisosRoute
  GateadoConciliacionesRoute: typeof GateadoConciliacionesRoute
  GateadoCuentasRoute: typeof GateadoCuentasRoute
  GateadoDashboardRoute: typeof GateadoDashboardRoute
  GateadoDiagnosticoRoute: typeof GateadoDiagnosticoRoute
  GateadoFacturasRoute: typeof GateadoFacturasRouteWithChildren
  GateadoFichaRoute: typeof GateadoFichaRoute
  GateadoInformesRoute: typeof GateadoInformesRoute
  GateadoMovimientosRoute: typeof GateadoMovimientosRoute
  GateadoProveedoresRoute: typeof GateadoProveedoresRoute
  GateadoSnapshotsRoute: typeof GateadoSnapshotsRoute
  GateadoTransferenciasRoute: typeof GateadoTransferenciasRoute
  GateadoValidacionRoute: typeof GateadoValidacionRoute
  GateadoVencimientosRoute: typeof GateadoVencimientosRoute
  GateadoIndexRoute: typeof GateadoIndexRoute
}

const GateadoRouteRouteChildren: GateadoRouteRouteChildren = {
  GateadoAuditoriaRoute: GateadoAuditoriaRoute,
  GateadoBackupRoute: GateadoBackupRoute,
  GateadoCategoriasRoute: GateadoCategoriasRoute,
  GateadoComparativaRoute: GateadoComparativaRoute,
  GateadoCompromisosRoute: GateadoCompromisosRoute,
  GateadoConciliacionesRoute: GateadoConciliacionesRoute,
  GateadoCuentasRoute: GateadoCuentasRoute,
  GateadoDashboardRoute: GateadoDashboardRoute,
  GateadoDiagnosticoRoute: GateadoDiagnosticoRoute,
  GateadoFacturasRoute: GateadoFacturasRouteWithChildren,
  GateadoFichaRoute: GateadoFichaRoute,
  GateadoInformesRoute: GateadoInformesRoute,
  GateadoMovimientosRoute: GateadoMovimientosRoute,
  GateadoProveedoresRoute: GateadoProveedoresRoute,
  GateadoSnapshotsRoute: GateadoSnapshotsRoute,
  GateadoTransferenciasRoute: GateadoTransferenciasRoute,
  GateadoValidacionRoute: GateadoValidacionRoute,
  GateadoVencimientosRoute: GateadoVencimientosRoute,
  GateadoIndexRoute: GateadoIndexRoute,
}

const GateadoRouteRouteWithChildren = GateadoRouteRoute._addFileChildren(
  GateadoRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  GateadoRouteRoute: GateadoRouteRouteWithChildren,
  UnlockRoute: UnlockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
